# wrangler.toml
name = "chats"
main = "src/worker.js"
compatibility_date = "2024-03-

[[durable_objects.bindings]]
name       = "CHAT_ROOM_DO"
class_name = "HibernatingChatRoom"

# --- 新增的继承配置 ---
[[durable_objects.bindings.migrations]]
# 这是一个特殊的“空”迁移，用于将环境变量附加到现有类
tag = "v5-inherit-secrets" # 使用一个新的、唯一的标签
# 从主Worker继承这些密钥
inherit = ["CRON_SECRET", "DEEPSEEK_API_KEY", "GEMINI_API_KEY"] 

[[r2_buckets]]
binding     = "R2_BUCKET"
bucket_name = "yuangs"

# wrangler.toml


# --- 新增：定时触发器配置 ---
[triggers]
# crons 是一个数组，您可以定义多个定时任务
# 格式是标准的 Cron 表达式: 分 时 日 月 周
# 下面这个例子表示：在每小时的第30分钟执行一次
crons = [ "*/1 * * * *" ]