# wrangler.toml
name = "chats"
main = "src/worker.js"
compatibility_date = "2024-03-01"

[[durable_objects.bindings]]
name       = "CHAT_ROOM_DO"
class_name = "HibernatingChatRoomV2"

[[r2_buckets]]
binding     = "R2_BUCKET"
bucket_name = "yuangs"

# wrangler.toml

[[migrations]]
tag = "v1"
new_sqlite_classes = [ "HibernatingChatRoomV2" ]