# wrangler.toml
name = "chats"
main = "src/worker.js"
compatibility_date = "2024-03-01"

[[durable_objects.bindings]]
name       = "CHAT_ROOM_DO"
class_name = "HibernatingChatRoom"

[[r2_buckets]]
binding     = "R2_BUCKET"
bucket_name = "yuangs"

# wrangler.toml

# 第一步：删除所有旧实例
[[migrations]]
tag          = "delete-hibernating-chatroom"
delete_class = "HibernatingChatRoom"