# The name of your Worker
name = "chats"

# The main entry point for your Worker
main = "src/worker.js"

# A recent compatibility date
compatibility_date = "2024-03-01"

# --- Durable Object Binding ---
[[durable_objects.bindings]]
name = "CHAT_ROOM_DO"
# Point to the NEW, final class name
class_name = "HibernatingChatRoom" 

# --- R2 Storage Bucket Binding ---
[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "yuangs"

# --- CORRECTED MIGRATION ---
# This single migration cleans up the conflicting history.
# It renames all possible old classes to the one final class.
[[migrations]]
# Use a new, unique tag that you haven't used before
tag = "v3-final-cleanup" 
# Define all renames to the final class
renamed_classes = [
  { from = "ChatRoom", to = "HibernatingChatRoom" },
  { from = "ChatRoomV2", to = "HibernatingChatRoom" }
]
