name = "chats"
main = "src/worker.js"
compatibility_date = "2024-07-08"

# 启用 nodejs_compat 以便 ECharts 库能正常工作
compatibility_flags = [ "nodejs_compat" ]

# 静态网站托管配置
[site]
bucket = "./public"

# Durable Object 绑定
[[durable_objects.bindings]]
name       = "CHAT_ROOM_DO"
class_name = "HibernatingChatRoom"
script_name = "chats"

# R2 存储桶绑定 (聊天媒体和图表共用)
[[r2_buckets]]
binding     = "R2_BUCKET"
bucket_name = "yuangs" # ✨ 请确保这是您正确的R2桶名

# 定时触发器
[triggers]
crons = [
  "0 9 * * *",# 文字任务：每天上午9点触发一次
  "0 9-15,21-3 * * *"  # 图片任务：9点到15点、21点到次日3点，整点触发
]