# The name of your Worker
name = "chats"

# The main entry point for your Worker
main = "src/worker.js"

# A recent compatibility date
compatibility_date = "2024-03-01"

# --- Durable Object Binding ---
[[durable_objects.bindings]]
name = "CHAT_ROOM_DO"
# The final, correct class name
class_name = "HibernatingChatRoom" 

# --- R2 Storage Bucket Binding ---
[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "yuangs"

# --- FINAL MIGRATION WITH HISTORY RESET ---
# This migration will resolve all conflicts.
[[migrations]]
# Use a new, unique tag for this final attempt.
tag = "v4-reset-and-consolidate" 

# THIS IS THE KEY: Explicitly delete the conflicting migration 
# histories of all old classes from the Cloudflare script.
# Add any other old class names you might have used.
delete_classes = ["ChatRoom", "ChatRoomV2", "ChatRoomDurableObject"]

# After the old histories are deleted, this defines the one true
# path forward for any existing Durable Object instances.
renamed_classes = [
  { from = "ChatRoom", to = "HibernatingChatRoom" },
  { from = "ChatRoomV2", to = "HibernatingChatRoom" }
]
