# =================================================================
#  wrangler.toml (The one and only correct version)
# =================================================================

# --- 基本信息 ---
name = "chats"
main = "src/worker.js"
compatibility_date = "2024-07-05" 

# --- 静态网站托管 ---
# 将 ./public 目录下的文件作为静态资源提供服务
[site]
bucket = "./public"

# --- Durable Object 绑定 ---
# 这是正确的、官方支持的写法
[[durable_objects.bindings]]
name       = "CHAT_ROOM_DO"
class_name = "HibernatingChatRoom"
# 关键：通过指定脚本名称，DO会自动继承该脚本的密钥和环境变量
script_name = "chats" 

# --- R2 存储桶绑定 ---
[[r2_buckets]]
binding     = "R2_BUCKET"
bucket_name = "yuangs"

# --- 定时触发器 ---
[triggers]
# 测试时可临时改为 "*/1 * * * *" (每分钟执行一次)。
crons = [ "*/2 * * * *" ]