# wrangler.toml for updated Wrangler version
name = "chats"
main = "src/worker.js"
compatibility_date = "2023-11-21"

# 自定义域名配置
routes = [
  { pattern = "chats.want.biz", custom_domain = true }
]

# 定义 Durable Object 类
[[durable_objects.bindings]]
name = "CHAT_ROOM_DO"
class_name = "HibernatingChatRoom"
script_name = "chats"  # 添加这一行，指定脚本名称

# R2 存储桶配置
[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "yuangs"

# 迁移配置 - 免费计划使用 SQLite 类
[[migrations]]
tag = "v2"
new_sqlite_classes = ["HibernatingChatRoom"]  # 免费计划必须使用 SQLite