# wrangler.toml
name = "chats"
main = "src/worker.js"
compatibility_date = "2024-03-01"

[[durable_objects.bindings]]
name       = "CHAT_ROOM_DO"
class_name = "HibernatingChatRoom"

[[r2_buckets]]
binding     = "R2_BUCKET"
bucket_name = "yuangs"

# wrangler.toml

# 第二步：在干净状态下启用 SQLite
[[migrations]]
tag               = "enable-sqlite"
new_sqlite_class  = "HibernatingChatRoom"