# Worker 的名称，将成为 URL 的一部分
name = "chatroom"

# Worker 的主入口文件路径
main = "src/worker.js"

# 兼容性日期，确保 Worker 在一个可预测的环境中运行
compatibility_date = "2023-10-26"

[vars]
GEMINI_API_KEY = "AIzaSyAdrZu2GiCsDenei4_qQLEAwLeO1lLwiSU"

# --- R2 存储桶绑定 ---
[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "yuangs"  # 您的 R2 存储桶名称

# --- Durable Object 绑定定义 ---
[[durable_objects.bindings]]
# 在 worker.js 中，我们将通过 env.CHAT_ROOM_DO 来访问这个 Durable Object
name = "CHAT_ROOM_DO" 
# 这个绑定对应于在代码中导出的类的名称
class_name = "ChatRoomDurableObject" 

# --- Durable Object 迁移配置 ---
# 这确保了我们的 Durable Object 使用更现代、更强大的基于 SQLite 的存储后端。
[[migrations]]
tag = "v1" 
new_sqlite_classes = ["ChatRoomDurableObject"]
