#!/usr/bin/env python3
"""
Minecraft Clone - 可视化安装向导
在浏览器中打开详细指南，提供清晰的步骤说明
"""

import webbrowser
import os

guide_path = "/Users/ygs/yuangs/minecraft-clone-project/QUICK_START.md"

print("=" * 60)
print("  🎮 Minecraft Clone 安装向导")
print("=" * 60)
print()

print("✅ 已自动完成：")
print("   ✓ 系统检查通过 (macOS 12.7.6)")
print("   ✓ 项目目录创建")
print("   ✓ 16 个 C# 脚本已复制")
print("   ✓ 项目配置文件已创建")
print("   ✓ 快速启动脚本已创建")
print()

print("⚠️  需要手动完成（Unity 必须通过 GUI 安装）：")
print()

print("=" * 60)
print("  第 1 步：下载并安装 Unity Hub（10 分钟）")
print("=" * 60)
print()
print("1. 点击这个链接下载 Unity Hub:")
print("   🔗 https://unity.com/download")
print()
print("2. 选择 'Unity Hub for macOS'")
print("3. 下载 .dmg 文件（约 100MB）")
print("4. 打开下载的文件，将 Unity Hub 拖到 Applications")
print("5. 打开 Unity Hub 应用")
print("6. 创建免费账号并登录")
print()

print("=" * 60)
print("  第 2 步：安装 Unity 2023 LTS（10-20 分钟）")
print("=" * 60)
print()
print("在 Unity Hub 中：")
print("   1. 点击左侧 'Installs' 标签")
print("   2. 点击 'Install Editor' 按钮")
print("   3. 找到 '2023 LTS' 或 '2023.2.0f1'")
print("   4. 点击齿轮 ⚙️ 图标，勾选：")
print("       ✅ Mac Build Support (IL2CPP)")
print("   5. 点击 'Install'")
print("   6. 等待下载完成（约 3-5GB）")
print()

print("=" * 60)
print("  第 3 步：打开项目（1 分钟）")
print("=" * 60)
print()
print("在 Unity Hub 中：")
print("   1. 点击 'Projects' 标签")
print("   2. 点击 'Add project from disk'")
print("   3. 选择这个文件夹：")
print("       📁 /Users/ygs/yuangs/minecraft-clone-project/MinecraftClone")
print("   4. 点击 'Open'")
print("   5. 等待 Unity 导入项目（1-2 分钟）")
print()

print("=" * 60)
print("  第 4 步：安装必需包（2 分钟）")
print("=" * 60)
print()
print("在 Unity 编辑器中：")
print("   1. 等待右下角显示 'Done'")
print("   2. 点击顶部菜单：")
print("       Window > Package Manager")
print("   3. 检查是否已安装：")
print("       ✓ TextMeshPro（默认已安装）")
print("   4. 如果没有，点击 '+' 搜索 'TextMeshPro' 并安装")
print()
print("注意：Burst 和 Job System 是 Unity 内置的，无需安装")
print()

print("=" * 60)
print("  第 5 步：测试运行（1 分钟）")
print("=" * 60)
print()
print("在 Unity 编辑器中：")
print("   1. 点击顶部播放按钮 ▶️")
print("   2. 按住鼠标左键锁定光标")
print("   3. 尝试使用 WASD 移动")
print("   4. 看是否能看到生成的地形")
print()

print("=" * 60)
print("  🎮 游戏控制")
print("=" * 60)
print()
print("按键        | 功能")
print("-" * 30)
print("W A S D      | 移动（前左后右）")
print("空格         | 跳跃")
print("Shift        | 加速")
print("鼠标移动     | 看四周")
print("鼠标左键    | 破坏方块")
print("鼠标右键    | 放置方块")
print("Q / E        | 切换方块类型")
print("ESC          | 释放光标")
print()

print("=" * 60)
print("  ⚠️  重要说明")
print("=" * 60)
print()
print("为什么需要手动安装 Unity？")
print("   • Unity Hub 是 GUI 应用程序，无法命令行安装")
print("   • Unity Editor 需要 GUI 操作，无法自动化")
print("   • 但我已经为你准备了所有代码和配置文件！")
print()
print("如果你运行 Unity 后遇到问题：")
print("   1. 查看 Console (Window > General > Console)")
print("   2. 截图并发给我错误信息")
print("   3. 我会立即帮你调试")
print()

print("=" * 60)
print("  📞 需要帮助？")
print("=" * 60)
print()
print("快速访问文件：")
print("   📖 完整指南: file:///Users/ygs/yuangs/minecraft-clone-project/QUICK_START.md")
print("   🚀 启动脚本: file:///Users/ygs/yuangs/minecraft-clone-project/launch-unity.sh")
print()

input("\n按回车键打开详细指南...")
print()

# 打开浏览器显示指南
os.system(f"open file://{guide_path}")

print()
print("=" * 60)
print("  ✅ 准备就绪！")
print("=" * 60)
print()
print("现在按照上述步骤操作，大约 30 分钟后就能开始游戏！")
print("祝玩得愉快！🎮✨")
